// Generated by scripts/build_learning.py; content: CC-BY-4.0
window.EDITOR8_LEARNING = {
  "course": {
    "version": 1,
    "synthetic": true,
    "title": "Ontologien verstehen und pflegen",
    "lessons": [
      {
        "id": "grundlagen",
        "title": "1. Was pflegen wir?",
        "goal": "Eine Vorlage von einer konkreten Akte unterscheiden.",
        "slides": [
          {
            "id": "grundlagen-1",
            "title": "Eine Ontologie macht Begriffe und Beziehungen eindeutig",
            "text": "Das Fachmodell beschreibt, welche Arten von Angaben, Dokumenten, Entscheidungen und Prüfungen zu einem Vorgang gehören. Die Fantasiewerkstatt ist unser vollständig künstliches Lernbeispiel.",
            "steps": [
              "Lies die fünf Bausteine rechts.",
              "Frage dich: Was soll eine Person mit diesem Modell verstehen können?"
            ],
            "focus": "local.schutz",
            "question": "Was wird hier gepflegt?",
            "choices": [
              "Eine Fachvorlage",
              "Eine konkrete Teilnehmerakte"
            ],
            "answer": 0,
            "explanation": "Wir pflegen wiederverwendbare Begriffe und Beziehungen. Reale Angaben einzelner Personen werden hier nicht erfasst."
          },
          {
            "id": "grundlagen-2",
            "title": "Vorlage und konkreter Wert haben verschiedene Aufgaben",
            "text": "„Benötigte Schutzausrüstung“ bezeichnet eine benötigte Angabe. „Helm der Teilnehmerin Lisa“ wäre ein konkreter Wert. Im Editor pflegen wir die Vorlage und ihre Bedeutung.",
            "steps": [
              "Formuliere die benötigte Angabe.",
              "Lass konkrete Namen, Aktenwerte und ausgefüllte Dokumente weg."
            ],
            "focus": "local.schutz",
            "question": "Welcher Inhalt passt in die Vorlage?",
            "choices": [
              "Name einer konkreten Person",
              "Erläuterung der benötigten Angabe"
            ],
            "answer": 1,
            "explanation": "Die Erläuterung beschreibt das Modell. Personenwerte gehören in eine dafür vorgesehene Anwendung."
          },
          {
            "id": "grundlagen-3",
            "title": "Eine Modelländerung beantwortet eine fachliche Frage",
            "text": "Beginne mit dem Zweck: Was fehlt, ist unklar oder stimmt nicht mehr? Suche zuerst einen vorhandenen Baustein. Ein neuer Baustein braucht einen eigenen fachlichen Gegenstand.",
            "steps": [
              "Beispiel: Die Schutzausrüstung ist zu unklar bezeichnet.",
              "Wir präzisieren die vorhandene Frage statt eine zweite gleiche Frage anzulegen."
            ],
            "focus": "local.schutz",
            "question": "Was ist der erste Schritt?",
            "choices": [
              "Sofort einen neuen Baustein anlegen",
              "Zweck klären und vorhandenes Modell prüfen"
            ],
            "answer": 1,
            "explanation": "Eine gezielte Änderung beginnt mit einer begründeten Lücke und vermeidet doppelte Begriffe."
          }
        ]
      },
      {
        "id": "baum",
        "title": "2. Baum und Bausteine",
        "goal": "Die passende Bausteinart auswählen.",
        "slides": [
          {
            "id": "baum-1",
            "title": "Der Baum sortiert nach der Art des Bausteins",
            "text": "Fragen, Dokumenttypen, Entscheidungen, Prüfschritte und Nachweistypen sind Kategorien. Ihre Position im Baum legt keine zeitliche Reihenfolge fest. Der Graph zeigt die fachlichen Beziehungen.",
            "steps": [
              "Wähle einen Baustein rechts durch Anklicken.",
              "Lies seine Kategorie und Erläuterung."
            ],
            "focus": "local.liste",
            "question": "Wo steht die Ausrüstungsliste?",
            "choices": [
              "Dokumenttypen",
              "Prüfschritte"
            ],
            "answer": 0,
            "explanation": "Die Liste ist eine Dokumentart. Das Prüfen der Liste wäre ein eigener Prüfschritt."
          },
          {
            "id": "baum-2",
            "title": "Dokumenttyp und Nachweistyp haben unterschiedliche Schwerpunkte",
            "text": "Ein Dokumenttyp beschreibt eine benötigte Dokumentart, etwa die Ausrüstungsliste. Ein Nachweistyp beschreibt einen Beleg für eine Angabe oder Prüfung, etwa den Prüfvermerk. Welche Rolle ein Artefakt hat, entscheidet das Fachmodell.",
            "steps": [
              "Prüfe, ob du eine Dokumentart oder die Art eines Belegs beschreibst.",
              "Bei Unklarheit eine offene Fachfrage dokumentieren."
            ],
            "focus": "local.vermerk",
            "question": "Was beschreibt „Prüfvermerk“ im Beispiel?",
            "choices": [
              "Eine tatsächlich abgeschlossene Prüfung",
              "Eine Art des möglichen Nachweises"
            ],
            "answer": 1,
            "explanation": "Der Nachweistyp ist eine Vorlage. Er bestätigt nicht, dass jemand die Prüfung bereits durchgeführt hat."
          },
          {
            "id": "baum-3",
            "title": "Eine Entscheidung wählt, ein Prüfschritt kontrolliert",
            "text": "„Leihmaterial auswählen“ beschreibt eine Auswahl. „Ausrüstung prüfen“ beschreibt eine Kontrolle. Ein Baum-Eintrag ist kein automatisch ausgeführter Arbeitsschritt. Abläufe bleiben im Prozessmodell.",
            "steps": [
              "Prüfe die Bedeutung der beiden Bausteine.",
              "Verschiebe einen Typ nur bei fachlich begründeter Änderung."
            ],
            "focus": "local.auswahl",
            "question": "Welcher Baustein beschreibt eine Auswahl?",
            "choices": [
              "Leihmaterial auswählen",
              "Ausrüstung prüfen"
            ],
            "answer": 0,
            "explanation": "Eine Entscheidung hat Alternativen. Ein Prüfschritt prüft Bedingungen oder Vollständigkeit."
          }
        ]
      },
      {
        "id": "beziehungen",
        "title": "3. Beziehungen lesen",
        "goal": "Quelle, Beziehung und Ziel als Satz lesen.",
        "slides": [
          {
            "id": "beziehungen-1",
            "title": "Eine Verbindung ist ein gerichteter Satz",
            "text": "Lies den Pfeil als Quelle, Beziehung, Ziel. Im Beispiel: „Benötigte Schutzausrüstung – belegt durch – Ausrüstungsliste“. Der Baum allein sagt diese Verbindung nicht aus.",
            "steps": [
              "Wähle die Frage als Quelle.",
              "Lies den Beziehungstyp und anschließend das Ziel."
            ],
            "focus": "local.schutz",
            "question": "Welche Richtung wird erklärt?",
            "choices": [
              "Frage wird durch Liste belegt",
              "Liste wird durch Frage belegt"
            ],
            "answer": 0,
            "explanation": "Die Pfeilrichtung gehört zur Aussage. Umkehren kann die Bedeutung verändern."
          },
          {
            "id": "beziehungen-2",
            "title": "Information und Voraussetzung sind verschiedene Aussagen",
            "text": "„Informiert“ beschreibt einen Informationsbezug. „Erfordert“ beschreibt eine benötigte Voraussetzung. „Wartet auf Prüfung“ ist eine modellierte Abhängigkeit. Der Editor führt dadurch keine Prüfung automatisch aus.",
            "steps": [
              "Wähle den Typ wegen seiner Bedeutung, nicht wegen der Pfeilfarbe.",
              "Bei mehreren möglichen Bedeutungen eine Fachfrage stellen."
            ],
            "focus": "local.auswahl",
            "question": "Was folgt aus einem Pfeil „informiert“?",
            "choices": [
              "Die Zielprüfung wurde durchgeführt",
              "Die Quelle liefert Informationen für das Ziel"
            ],
            "answer": 1,
            "explanation": "Die Beziehung beschreibt einen Zusammenhang im Modell und keinen erledigten Vorgang."
          },
          {
            "id": "beziehungen-3",
            "title": "Neue Beziehungen brauchen zwei vorhandene Bausteine",
            "text": "Im Editor öffnest du Ansicht → Verbindungen und wählst Quelle, Typ und Ziel. Prüfe den Satz vor dem Hinzufügen. Eine sachlich passende Verbindung kann Kategorien übergreifen.",
            "steps": [
              "Suche Quelle und Ziel anhand ihrer Bezeichnungen.",
              "Prüfe Richtung und Typ im gespeicherten Vergleich."
            ],
            "focus": "local.pruefung",
            "question": "Was muss vor dem Hinzufügen feststehen?",
            "choices": [
              "Nur der Name des Ziels",
              "Quelle, Beziehungstyp und Ziel"
            ],
            "answer": 1,
            "explanation": "Alle drei Teile bilden gemeinsam die fachliche Aussage."
          }
        ]
      },
      {
        "id": "pflegen",
        "title": "4. Gezielt bearbeiten",
        "goal": "Eine kleine begründete Änderung vorbereiten.",
        "slides": [
          {
            "id": "pflegen-1",
            "title": "Der erste Pflegefall präzisiert eine Bezeichnung",
            "text": "Unser künstlicher Anlass: Die Frage soll ausdrücklich Schutzausrüstung für den Workshop betreffen. Vorher: „Benötigte Schutzausrüstung“. Nachher: „Benötigte Schutzausrüstung für den Workshop“.",
            "steps": [
              "Öffne Bearbeiten und wähle den vorhandenen Baustein.",
              "Wähle Entwurf erstellen oder Bearbeiten am Baustein."
            ],
            "focus": "local.schutz",
            "question": "Brauchen wir dafür einen zweiten Baustein?",
            "choices": [
              "Ja, bei jeder Umbenennung",
              "Nein, die Bedeutung bleibt derselbe Gegenstand"
            ],
            "answer": 1,
            "explanation": "Wir präzisieren die Bezeichnung des vorhandenen Bausteins und behalten seine Kennung und Beziehungen."
          },
          {
            "id": "pflegen-2",
            "title": "Eine Erläuterung macht den Pflegegrund nachvollziehbar",
            "text": "Bezeichnung ist der kurze sichtbare Name. Fachliche Erläuterung erklärt seine Bedeutung. Offene Fachfrage hält eine ungelöste Frage fest. Der Status einer übernommenen NaC-Vorlage ist im Formular schreibgeschützt.",
            "steps": [
              "Ändere nur die begründeten Felder.",
              "Dokumentiere Unsicherheit als offene Frage statt eine Antwort zu erfinden."
            ],
            "focus": "local.schutz",
            "question": "Wo gehört eine ungelöste Bedeutungsfrage hin?",
            "choices": [
              "Offene Fachfrage",
              "Als erfundene Entscheidungsoption"
            ],
            "answer": 0,
            "explanation": "Eine offene Frage bleibt sichtbar und kann fachlich geprüft werden."
          },
          {
            "id": "pflegen-3",
            "title": "Neue Bausteine und Löschungen ändern die Struktur",
            "text": "Ein neuer Baustein ist sinnvoll, wenn ein eigenständiger Gegenstand fehlt. Seine Kategorie, Bezeichnung und Beziehungen müssen erklärt werden. Beim Löschen müssen auch betroffene Beziehungen und Quellen geprüft werden.",
            "steps": [
              "Suche vor dem Anlegen nach ähnlichen Bausteinen.",
              "Prüfe nach der Änderung, ob Nachbarn oder Bezüge fehlen."
            ],
            "focus": "local.liste",
            "question": "Wann ist ein neuer Baustein begründet?",
            "choices": [
              "Ein eigenständiger benötigter Gegenstand fehlt",
              "Die alte Bezeichnung gefällt nicht"
            ],
            "answer": 0,
            "explanation": "Eine Umbenennung ist eine Feldänderung. Ein neuer Gegenstand ist eine Strukturänderung."
          }
        ]
      },
      {
        "id": "speichern",
        "title": "5. Speichern und prüfen",
        "goal": "Browser-Eingabe, Entwurf und Freigabe unterscheiden.",
        "slides": [
          {
            "id": "speichern-1",
            "title": "Speichern zeigt zuerst den Vergleich",
            "text": "Ungespeicherte Eingaben sind zunächst Browserzustand. Datei → Speichern oder Strg+S öffnet die fachliche Vorschau. Erst die Bestätigung schreibt in deinen Datenentwurf.",
            "steps": [
              "Vergleiche alte und neue Bezeichnung.",
              "Prüfe, ob weitere unbeabsichtigte Änderungen auftauchen."
            ],
            "focus": "local.schutz",
            "question": "Wann wird der Datenentwurf aktualisiert?",
            "choices": [
              "Beim Tippen jedes Buchstabens",
              "Nach Bestätigung der Speichervorschau"
            ],
            "answer": 1,
            "explanation": "Die Vorschau ist eine Kontrolle vor dem Schreiben in den Entwurfszweig."
          },
          {
            "id": "speichern-2",
            "title": "Ein gespeicherter Entwurf ist noch keine freigegebene Vorlage",
            "text": "Unter Prüfen → Meine Änderung begründest du die Änderung und nennst den Quellenstand. Einreichen erzeugt einen Pull Request im Datenrepository. Eine andere Person prüft den aktuellen Commit.",
            "steps": [
              "Grund: Bezeichnung im künstlichen Workshop präzisiert.",
              "Quelle: künstliche Trainingsbeschreibung, keine Rechtsquelle."
            ],
            "focus": "local.schutz",
            "question": "Erteilt Speichern eine notarielle Freigabe?",
            "choices": [
              "Nein",
              "Ja"
            ],
            "answer": 0,
            "explanation": "Speichern, Einreichen, fachliche Freigabe und Übernahme sind getrennte Schritte."
          },
          {
            "id": "speichern-3",
            "title": "Eine neue Änderung braucht eine Prüfung des neuen Stands",
            "text": "Freigaben beziehen sich auf einen geprüften Commit. Eine spätere Änderung kann eine erneute Prüfung nötig machen. Der vereinbarte manuelle Merge-Weg bleibt Aufgabe einer berechtigten Person.",
            "steps": [
              "Prüfe Begriffe, Quellen und Beziehungen.",
              "Prüfe vor Übernahme den tatsächlichen Commit und die CI."
            ],
            "focus": "local.pruefung",
            "question": "Welcher Stand ist für eine Freigabe maßgeblich?",
            "choices": [
              "Der aktuelle geprüfte Commit",
              "Irgendeine frühere Ansicht"
            ],
            "answer": 0,
            "explanation": "Eine Freigabe ist nur aussagekräftig, wenn erkennbar ist, welcher Stand geprüft wurde."
          }
        ]
      },
      {
        "id": "routine",
        "title": "6. Pflege im Alltag",
        "goal": "Eine Änderung vollständig und wiederholbar abschließen.",
        "slides": [
          {
            "id": "routine-1",
            "title": "Ein kleiner Pflegeauftrag ist leichter zu prüfen",
            "text": "Beschreibe Anlass, betroffene Vorgangsart und erwartete Änderung vor dem Bearbeiten. Halte Fachquellen und Software-Release auseinander. Ein Entwurf sollte einen klaren fachlichen Zweck haben.",
            "steps": [
              "Notiere die fragliche Bezeichnung oder Verbindung.",
              "Nenne den erwarteten Unterschied in einem Satz."
            ],
            "focus": "local.schutz",
            "question": "Welche Kennung beschreibt die Software?",
            "choices": [
              "Editor-Release",
              "Die Bezeichnung eines Bausteins"
            ],
            "answer": 0,
            "explanation": "Editor-Release bezeichnet die Software. Der Datencommit bezeichnet den Fachmodellstand."
          },
          {
            "id": "routine-2",
            "title": "Beispiele erklären Funktionen ohne echte Daten zu ändern",
            "text": "Die Übung in diesem Training verändert nur das künstliche Beispiel im Speicher des Browsers. Sie meldet sich nicht bei GitHub an und erzeugt weder Branches noch Pull Requests. Neu laden setzt sie zurück.",
            "steps": [
              "Wähle unten „Bezeichnung üben“.",
              "Ändere die Beispielbezeichnung, prüfe den Vergleich und bestätige Speichern."
            ],
            "focus": "local.schutz",
            "question": "Wo wird diese Übung gespeichert?",
            "choices": [
              "Im echten Datenrepository",
              "Nur im Browser bis zum Neuladen"
            ],
            "answer": 1,
            "explanation": "Der Trainingsbereich ist eine geschützte Erklärung mit künstlichen Beispielen."
          },
          {
            "id": "routine-3",
            "title": "Die Pflege endet mit einem nachgewiesenen Ergebnis",
            "text": "Für Modellpflege zählt der geprüfte Datenstand. Für Software zählt die gesunde Azure-Revision mit passender Release-Kennung. Bei einer Fehlermeldung bewahre den Entwurf und dokumentiere Schritt und Meldung.",
            "steps": [
              "Nutze das Handbuch für Rollen und Fehlerbehebung.",
              "Prüfe eine kleine konkrete Änderung statt mehrere Themen gleichzeitig."
            ],
            "focus": "local.vermerk",
            "question": "Was gehört zur dokumentierten Modelländerung?",
            "choices": [
              "Grund, Quelle, Änderung und geprüfter Stand",
              "Nur eine neue Überschrift"
            ],
            "answer": 0,
            "explanation": "Eine nachvollziehbare Pflege verbindet die fachliche Begründung mit der tatsächlichen Änderung und Prüfung."
          }
        ]
      }
    ]
  },
  "example": {
    "synthetic": true,
    "title": "Künstliches Beispiel: Fantasiewerkstatt",
    "nodes": [
      {
        "id": "local.schutz",
        "category": "required_information",
        "label": "Benötigte Schutzausrüstung",
        "detail": "Fragevorlage: Welche Schutzausrüstung ist für die Übung vorgesehen?"
      },
      {
        "id": "local.liste",
        "category": "documents",
        "label": "Ausrüstungsliste",
        "detail": "Dokumentart mit den vorgesehenen Ausrüstungsarten."
      },
      {
        "id": "local.auswahl",
        "category": "decisions",
        "label": "Leihmaterial auswählen",
        "detail": "Entscheidungsvorlage: eigene Ausrüstung oder Leihmaterial."
      },
      {
        "id": "local.pruefung",
        "category": "gates",
        "label": "Ausrüstung prüfen",
        "detail": "Prüfvorlage: Ausrüstungsliste und Auswahl auf Übereinstimmung prüfen."
      },
      {
        "id": "local.vermerk",
        "category": "evidence",
        "label": "Prüfvermerk",
        "detail": "Nachweisart, die eine durchgeführte Prüfung dokumentieren würde."
      }
    ],
    "edges": [
      {
        "from": "local.schutz",
        "relation": "belegtDurch",
        "to": "local.liste"
      },
      {
        "from": "local.auswahl",
        "relation": "informiert",
        "to": "local.pruefung"
      },
      {
        "from": "local.pruefung",
        "relation": "belegtDurch",
        "to": "local.vermerk"
      }
    ]
  },
  "handbook": {
    "version": 1,
    "title": "editor8 Produkthandbuch",
    "chapters": [
      {
        "id": "ueberblick",
        "title": "Produkt und Zweck",
        "paragraphs": [
          "editor8 ist eine gehostete Arbeitsoberfläche für versionierte Fachvorlagen. Eine Ontologie benennt die Gegenstände eines Fachgebiets, ihre Eigenschaften und ihre Beziehungen so, dass Menschen und Software dieselben Kennungen verwenden können.",
          "Der Editor pflegt das Fachmodell eines Vorgangs. Die tatsächlichen Antworten einer Person, eine ausgefüllte Akte oder ein erledigter Prüfschritt werden dadurch nicht gespeichert. Im Notardatenprojekt liegen 20 kanonische Vorgangsarten. Weitere Datenziele benötigen den passenden Datenvertrag; der Editor hat keine feste Fallanzahl.",
          "Software und Fachmodelle liegen in getrennten Repositories. GitHub ist Pflege- und Versionsquelle für Daten. NaC bleibt Quelle für Prozessabläufe. Der Trainingsbereich verwendet ausschließlich künstliche Beispiele."
        ],
        "steps": [],
        "facts": [
          [
            "Software",
            "Oberfläche, Anmeldung, Adapter, Tests, Betrieb und Editor-Release."
          ],
          [
            "Datenrepository",
            "Fachmodelle, Katalog und Datencommit."
          ],
          [
            "Prozessmodell",
            "Beschreibt den Ablauf; der Baum im Editor ordnet Bausteine nach Art."
          ]
        ]
      },
      {
        "id": "einstieg",
        "title": "Einstieg und Orientierung",
        "paragraphs": [
          "Öffne https://www.ontologie8.de und melde dich mit deinem zugelassenen GitHub-Konto an. Die bisherige Azure-Adresse führt die Anmeldung zuerst zur aktuellen Domain, damit Anmelde-Cookie und Rückkehradresse zusammenpassen. Die Repository-Auswahl zeigt nur erlaubte und für dein Konto zugängliche Datenziele. Ein Eintrag in der Liste erteilt keine GitHub-Rechte.",
          "Links außen liegen Verstehen, Bearbeiten und Prüfen. Daneben stehen Datenrepository und Baum. In der Mitte liegt der Graph beziehungsweise die Arbeitsansicht. Rechts stehen Details oder Formular. Allgemeine Hilfe steht oben; das Fragezeichen am ausgewählten Baustein öffnet Kontexthilfe.",
          "Das Menüband wird mit Strg+F1 oder Doppelklick reduziert. Eine Registerkarte öffnet die Befehle vorübergehend. Das Hamburger-Menü schaltet den inneren Datenbaum unabhängig davon. Menüs und Auswahl bleiben erreichbar, während Inhalte innerhalb ihrer Bereiche scrollen."
        ],
        "steps": [
          "Datenrepository auswählen und eine Vorgangsart öffnen.",
          "Im Baum einen Baustein wählen; Kategorie, Bedeutung und Beziehungen rechts prüfen.",
          "Informationen öffnen, um Beschreibung, Quellen und Verlauf zu lesen.",
          "Hilfe → Training für den Grundkurs oder Hilfe → Handbuch für die Referenz öffnen."
        ],
        "facts": [
          [
            "Strg+K / Eingabetaste in Suche",
            "Bausteine im gesamten Datenkatalog suchen."
          ],
          [
            "Strg+S",
            "Speichervorschau öffnen."
          ],
          [
            "Datei → Drucken",
            "Lesefassung der aktuellen Auswahl drucken."
          ],
          [
            "Editor-Release",
            "Softwarecommit in der Fußzeile; der Datencommit ist eine andere Kennung."
          ]
        ]
      },
      {
        "id": "modell",
        "title": "Bausteine und Beziehungen",
        "paragraphs": [
          "Der Baum ist eine gegliederte Übersicht. Er zeigt keine Ausführungsreihenfolge und keine Klassenhierarchie eines allgemeinen OWL-Editors. Derselbe fachliche Graph kann mehrere Kategorien verbinden.",
          "Fragen im Baum entsprechen Angabenfragen im Datenmodell: Sie beschreiben, welche Angabe benötigt wird. Die Antwort eines Einzelfalls gehört nicht in die Vorlage. Dokumenttypen beschreiben Dokumentarten. Entscheidungen beschreiben Auswahlpunkte. Prüfschritte beschreiben Prüfbedingungen oder Gates. Nachweistypen beschreiben Arten von Belegen.",
          "Ein Dokument kann in einem Fachmodell zugleich eine Belegfunktion haben. Die richtige Modellierung hängt vom Zweck ab; der Kategoriename allein entscheidet das nicht. Bei Unklarheit zuerst die fachliche Bedeutung klären.",
          "Lies jede Verbindung als Quelle – Beziehung – Ziel. Zum Beispiel: „Benötigte Schutzausrüstung“ wird durch „Ausrüstungsliste“ belegt. Ein Pfeil definiert eine Aussage im Modell; er führt keinen Vorgang aus und bestätigt keine erledigte Prüfung."
        ],
        "steps": [],
        "facts": [
          [
            "Fragen",
            "Welche Information wird benötigt? Beispiel: benötigte Schutzausrüstung."
          ],
          [
            "Dokumenttypen",
            "Welche Art von Dokument wird benötigt? Beispiel: Ausrüstungsliste."
          ],
          [
            "Entscheidungen",
            "Welche Auswahl wird beschrieben? Beispiel: Leihmaterial auswählen."
          ],
          [
            "Prüfschritte",
            "Welche Bedingung soll geprüft werden? Beispiel: Ausrüstung prüfen."
          ],
          [
            "Nachweistypen",
            "Welche Art von Beleg wäre vorgesehen? Beispiel: Prüfvermerk."
          ],
          [
            "erfordert",
            "Quelle benötigt das Ziel als Voraussetzung."
          ],
          [
            "informiert",
            "Quelle liefert Informationen für das Ziel."
          ],
          [
            "belegt durch",
            "Quelle wird durch das Ziel belegt."
          ],
          [
            "wartet auf vollständige Angaben / wartet auf Prüfung",
            "Modellierte Abhängigkeit, keine automatisierte Prüfung."
          ],
          [
            "erfordert Entscheidung / füllt / bestimmt",
            "Weitere vom Adapter angebotene Beziehungen; Bedeutung und Richtung vor Änderung prüfen."
          ]
        ]
      },
      {
        "id": "pflege",
        "title": "Modellpflege Schritt für Schritt",
        "paragraphs": [
          "Beginne mit einem kleinen Auftrag: Welche Bezeichnung, Erläuterung oder Beziehung ist unklar? Was soll sich fachlich ändern? Suche zuerst vorhandene Bausteine, um Doppelungen zu vermeiden.",
          "Eine Umbenennung präzisiert einen vorhandenen Gegenstand. Ein neuer Baustein ist begründet, wenn ein eigenständiger Gegenstand fehlt. Kategorie, Kennung, Bedeutung und Beziehungen gehören dann zur Änderung. Vor Löschen die betroffenen Beziehungen und Quellen prüfen.",
          "Die Übung „Fantasiewerkstatt“ präzisiert „Benötigte Schutzausrüstung“ zu „Benötigte Schutzausrüstung für den Workshop“. Bedeutung und Kennung bleiben erhalten. Das Training zeigt die Änderung ausschließlich im Browser und schreibt keine GitHub-Daten."
        ],
        "steps": [
          "Vorgangsart und betroffenen Baustein unter Verstehen prüfen.",
          "Links Bearbeiten wählen und Entwurf erstellen oder Bearbeiten am Baustein öffnen.",
          "Bezeichnung und fachliche Erläuterung gezielt pflegen; ungelöste Bedeutung als Offene Fachfrage dokumentieren.",
          "Für eine Verbindung Ansicht → Verbindungen öffnen, Quelle, Typ und Ziel wählen und den Satz prüfen.",
          "Datei → Speichern wählen, alle Unterschiede prüfen und erst dann die Vorschau bestätigen.",
          "Unter Prüfen → Meine Änderung Grund und Quellenstand erfassen und die gespeicherte Änderung einreichen."
        ],
        "facts": [
          [
            "Keine neue Vorgangsart im Editor",
            "Die Anlage beziehungsweise Umfangsänderung eines Datenkatalogs erfolgt im Datenprojekt."
          ],
          [
            "Gemeinsame Begriffe",
            "Änderungen am Vokabular haben eigene Entwürfe und benötigen die Maintainer-Rolle."
          ],
          [
            "Kennungen",
            "Stabile Identität des Gegenstands; eine Änderung der Bezeichnung ersetzt keine Kennung."
          ]
        ]
      },
      {
        "id": "felder",
        "title": "Feldreferenz",
        "paragraphs": [
          "Das Formular zeigt die Felder des ausgewählten Bausteins. Pflegen bedeutet, eine fachliche Aussage nachvollziehbar zu beschreiben; nicht jedes Feld muss für jeden Typ ausgefüllt sein.",
          "Übernommene NaC-Kennungen und der Status einer NaC-Vorlage sind geschützt. Technische Entscheidungswerte bleiben unverändert, solange fachlich geprüfte Anzeigenamen fehlen. Die Anzeige der RDF-Verwendung beschreibt technische Modellbezüge und keine tatsächlichen Aktenzugriffe."
        ],
        "steps": [],
        "facts": [
          [
            "Bezeichnung",
            "Kurzer verständlicher Name. Beispiel: Benötigte Schutzausrüstung für den Workshop."
          ],
          [
            "Bausteintyp",
            "Kategorie des Gegenstands; Änderungen daran brauchen eine fachliche Begründung."
          ],
          [
            "Fachliche Erläuterung",
            "Bedeutung und Abgrenzung des Bausteins."
          ],
          [
            "Offene Fachfrage",
            "Ungelöste Modellierungsfrage, keine erfundene Antwort."
          ],
          [
            "Abschnitt der Vorlage",
            "Bezug zum Abschnitt der fachlichen Vorlage."
          ],
          [
            "Status der NaC-Vorlage",
            "Quellstatus; bei übernommenen Bausteinen schreibgeschützt."
          ],
          [
            "Pflegestatus des lokalen Entwurfs",
            "Status eines lokal ergänzten Bausteins."
          ],
          [
            "Verantwortliche Rolle",
            "Rolle für die betreffende Angabe oder Prüfung."
          ],
          [
            "Datenschutzklasse / Kann Personendaten enthalten?",
            "Klassifikation des Typs; hier keine tatsächlichen Personendaten eintragen."
          ],
          [
            "Benötigt für / Entscheidungsoptionen",
            "Eine Angabe pro Zeile; bestehende Maschinenwerte nicht frei übersetzen."
          ],
          [
            "Dokumentquelle",
            "Quellenbezug des Dokumenttyps."
          ],
          [
            "Grund und Quellenstand beim Einreichen",
            "Warum sich das Modell ändert und auf welche fachliche Quelle die Änderung gestützt wird."
          ]
        ]
      },
      {
        "id": "pruefen",
        "title": "Entwurf, Prüfung und Übernahme",
        "paragraphs": [
          "Tippen verändert zunächst den Browserzustand. Speichern öffnet die fachliche Vorschau. Bestätigung schreibt in deinen Entwurfszweig im Datenrepository. Einreichen erzeugt einen Pull Request. Diese Schritte erteilen keine notarielle Freigabe.",
          "Eine andere berechtigte Person prüft die eingereichte Änderung. Fachliche Freigaben sind für eingetragene Notarkonten vorgesehen und beziehen sich auf den geprüften Commit. Änderungen nach der Prüfung benötigen eine Beurteilung des neuen Stands.",
          "Der vereinbarte Pilot verwendet einen manuellen Merge-Weg: verantwortliche Person prüft fachliche Freigabe auf dem aktuellen Commit und erfolgreiche CI vor Übernahme. Eine technisch erzwungene GitHub-Mergesperre ist eine separate optionale Betriebsentscheidung.",
          "Eigene gespeicherte Entwürfe lassen sich wieder öffnen oder ablegen. Ungespeicherte Eingaben sind nach Browserverlust nicht dauerhaft gesichert. Eine frühere Fassung erzeugt einen neuen Prüfentwurf nach Vergleich und ersetzt main nicht direkt."
        ],
        "steps": [
          "Änderungsgrund und fachlichen Quellenstand lesen.",
          "Begriffe, Quellen und Beziehungen mit dem aktuellen Datencommit vergleichen.",
          "Als andere berechtigte Person eine begründete Rückfrage oder Freigabe dokumentieren.",
          "Bei neuem Commit den neuen Stand erneut prüfen.",
          "Vor manuellem Merge Freigabe, Dateiumfang und CI bestätigen."
        ],
        "facts": []
      },
      {
        "id": "rollen",
        "title": "Zugriff und Betrieb",
        "paragraphs": [
          "Die Anmeldung identifiziert den GitHub-Benutzer. Der Host erlaubt Benutzer über EDITOR_USERS. Das Datenrepository benötigt Read zum Lesen und Write zum Erstellen von Änderungen. Der GitHub-App-Benutzertoken ist auf die gemeinsamen Rechte von App und Benutzer beschränkt.",
          "Die Reviewer-Rolle erlaubt fachliche Freigaben einer anderen Person; die Maintainer-Rolle erlaubt gemeinsame Begriffe. Rollen erteilen keine GitHub-Rechte. Weitere Datenziele brauchen Registry-Eintrag, App-Installation, Benutzerzugriff und passenden Adapter.",
          "Der Editor läuft auf Azure. Secrets bleiben im Host. Lokale Entwicklung verlangt einen ausdrücklich separaten EDITOR8_DATA_ROOT. Die öffentliche Software-CI verwendet künstliche Daten; die Integration mit privaten Fachmodellen läuft im privaten Datenrepository.",
          "Ein Softwarebuild endet erst mit dem erwarteten Azure-Image, aktiver gesunder Revision und passender Release-Kennung. Konfiguration und Betriebsanleitung stehen in docs/editor-hosting.md und docs/data-repositories-and-users.md."
        ],
        "steps": [],
        "facts": [
          [
            "Leser",
            "Zugelassenes GitHub-Konto mit Lesezugriff am Datenziel."
          ],
          [
            "Bearbeitende",
            "Zusätzlicher GitHub-Schreibzugriff für Entwürfe und PRs."
          ],
          [
            "Notarielle Reviewer",
            "Zusätzliche fachliche Rolle; keine Selbstfreigabe."
          ],
          [
            "Ontology-Maintainer",
            "Zusätzliche Rolle für das gemeinsame Vokabular."
          ]
        ]
      },
      {
        "id": "fehler",
        "title": "Fehlerbehebung und Grenzen",
        "paragraphs": [
          "Wenn ein Schritt scheitert, dokumentiere Software-Release, Datenziel, Arbeitsschritt und genaue Fehlermeldung. Keine Tokens, Callback-URLs oder Secrets in Kommentare kopieren. Bewahre gespeicherte Entwürfe, solange die Ursache unklar ist.",
          "Der Editor bietet derzeit Textvergleich, Fachgraph und strukturierte Felder. Grafischer Vorher/Nachher-Vergleich, Rückfragen direkt am Baustein, kontrollierte deutsche Beziehungssätze und SHACL sind spätere Roadmap-Pakete.",
          "Der echte angemeldete Schreib-/PR-Weg und die notarielle Zwei-Personen-Abnahme bleiben gesonderte Nachweise. Die Trainingsübung und grüne technische Tests ersetzen diese Abnahmen nicht."
        ],
        "steps": [],
        "facts": [
          [
            "Anmeldung nicht abgeschlossen",
            "Auf der Fehlerseite Erneut anmelden wählen; eine alte Callback-Adresse nicht erneut öffnen. Bei erneutem Fehler nur Fehlermeldung und Diagnose-Kennung melden. Der Betreiber findet damit den fehlgeschlagenen Schritt, ohne Anmeldedaten zu protokollieren."
          ],
          [
            "Datenziel fehlt",
            "Registry-Eintrag, Benutzerzulassung, GitHub-Zugriff und App-Installation durch Betreiber prüfen lassen."
          ],
          [
            "Speichern deaktiviert",
            "Keine ungespeicherte Änderung oder kein passender Entwurf; aktive Vorgangsart und Entwurfszweck prüfen."
          ],
          [
            "Stand hat sich inzwischen geändert",
            "Nicht wiederholt überschreiben; aktuellen Datenstand neu prüfen und Entwurf vergleichen."
          ],
          [
            "Freigabe deaktiviert",
            "Eigene Änderung, fehlende Reviewer-Rolle, ungeklärter Befund oder nicht freigabefähiger PR."
          ],
          [
            "Repository-Wechsel blockiert",
            "Zuerst offene Eingaben speichern oder verwerfen und den Entwurf ablegen."
          ],
          [
            "Alte Oberfläche",
            "Editor-Release vergleichen und Browser neu laden; bei abweichender Kennung Betreiber informieren."
          ],
          [
            "Training zurückgesetzt",
            "Übungen sind flüchtig. Neu laden startet das künstliche Beispiel neu."
          ]
        ]
      }
    ]
  },
  "categories": {
    "required_information": "Angabenfragen",
    "documents": "Dokumenttypen",
    "decisions": "Entscheidungen",
    "gates": "Prüfgates",
    "evidence": "Nachweistypen"
  }
};
