// Generated by scripts/build_learning.py; content: CC-BY-4.0
window.EDITOR8_LEARNING = {
  "course": {
    "version": 1,
    "synthetic": true,
    "title": "Ontologien verstehen und pflegen",
    "lessons": [
      {
        "id": "grundlagen",
        "title": "1. Was pflegen wir?",
        "goal": "Als Ontologiepfleger oder Notar eine Fachvorlage von einer konkreten Akte unterscheiden.",
        "slides": [
          {
            "id": "grundlagen-1",
            "title": "Eine Ontologie macht Begriffe und Beziehungen eindeutig",
            "text": "Dieser Kurs richtet sich an Ontologiepfleger und Notare. Du pflegst die Begriffe und Beziehungen eines Fachmodells: Welche Angaben, Dokumenttypen, Entscheidungen und Prüfungen gehören zu einem Vorgang? Die Fantasiewerkstatt ist unser vollständig künstliches Lernbeispiel.",
            "steps": [
              "Lies die fünf Bausteine rechts.",
              "Frage dich: Was soll eine Person mit diesem Modell verstehen können?"
            ],
            "focus": "local.schutz",
            "question": "Was wird hier gepflegt?",
            "choices": [
              "Eine Fachvorlage",
              "Eine konkrete Teilnehmerakte"
            ],
            "answer": 0,
            "explanation": "Wir pflegen wiederverwendbare Begriffe und Beziehungen. Reale Angaben einzelner Personen werden hier nicht erfasst."
          },
          {
            "id": "grundlagen-2",
            "title": "Vorlage und konkreter Wert haben verschiedene Aufgaben",
            "text": "„Benötigte Schutzausrüstung“ bezeichnet eine benötigte Angabe. „Helm der Teilnehmerin Lisa“ wäre ein konkreter Wert. Im Editor pflegen wir die Vorlage und ihre Bedeutung.",
            "steps": [
              "Formuliere die benötigte Angabe.",
              "Lass konkrete Namen, Aktenwerte und ausgefüllte Dokumente weg."
            ],
            "focus": "local.schutz",
            "question": "Welcher Inhalt passt in die Vorlage?",
            "choices": [
              "Name einer konkreten Person",
              "Erläuterung der benötigten Angabe"
            ],
            "answer": 1,
            "explanation": "Die Erläuterung beschreibt das Modell. Personenwerte gehören in eine dafür vorgesehene Anwendung."
          },
          {
            "id": "grundlagen-3",
            "title": "Eine Modelländerung beantwortet eine fachliche Frage",
            "text": "Beginne mit dem Zweck: Was fehlt, ist unklar oder stimmt nicht mehr? Suche zuerst einen vorhandenen Baustein. Ein neuer Baustein braucht einen eigenen fachlichen Gegenstand.",
            "steps": [
              "Beispiel: Die Schutzausrüstung ist zu unklar bezeichnet.",
              "Wir präzisieren die vorhandene Frage statt eine zweite gleiche Frage anzulegen."
            ],
            "focus": "local.schutz",
            "question": "Was ist der erste Schritt?",
            "choices": [
              "Sofort einen neuen Baustein anlegen",
              "Zweck klären und vorhandenes Modell prüfen"
            ],
            "answer": 1,
            "explanation": "Eine gezielte Änderung beginnt mit einer begründeten Lücke und vermeidet doppelte Begriffe."
          }
        ]
      },
      {
        "id": "baum",
        "title": "2. Baum und Bausteine",
        "goal": "Die passende Bausteinart auswählen.",
        "slides": [
          {
            "id": "baum-1",
            "title": "Der Baum sortiert nach der Art des Bausteins",
            "text": "Fragen, Dokumenttypen, Entscheidungen, Prüfschritte und Nachweistypen sind Kategorien. Ihre Position im Baum legt keine zeitliche Reihenfolge fest. Der Graph zeigt die fachlichen Beziehungen.",
            "steps": [
              "Wähle einen Baustein rechts durch Anklicken.",
              "Lies seine Kategorie und Erläuterung.",
              "Im Editor: Halte den Mauszeiger über einen Baustein für einen kurzen Hinweis; Rechtsklick oder Umschalt+F10 zeigt dessen Befehle."
            ],
            "focus": "local.liste",
            "question": "Wo steht die Ausrüstungsliste?",
            "choices": [
              "Dokumenttypen",
              "Prüfschritte"
            ],
            "answer": 0,
            "explanation": "Die Liste ist eine Dokumentart. Das Prüfen der Liste wäre ein eigener Prüfschritt."
          },
          {
            "id": "baum-2",
            "title": "Dokumenttyp und Nachweistyp haben unterschiedliche Schwerpunkte",
            "text": "Ein Dokumenttyp beschreibt eine benötigte Dokumentart, etwa die Ausrüstungsliste. Ein Nachweistyp beschreibt einen Beleg für eine Angabe oder Prüfung, etwa den Prüfvermerk. Welche Rolle ein Dokument hat, entscheidet sein Zweck im Fachmodell.",
            "steps": [
              "Prüfe, ob du eine Dokumentart oder die Art eines Belegs beschreibst.",
              "Bei Unklarheit eine offene Fachfrage dokumentieren."
            ],
            "focus": "local.vermerk",
            "question": "Was beschreibt „Prüfvermerk“ im Beispiel?",
            "choices": [
              "Eine tatsächlich abgeschlossene Prüfung",
              "Eine Art des möglichen Nachweises"
            ],
            "answer": 1,
            "explanation": "Der Nachweistyp ist eine Vorlage. Er bestätigt nicht, dass jemand die Prüfung bereits durchgeführt hat."
          },
          {
            "id": "baum-3",
            "title": "Eine Entscheidung wählt, ein Prüfschritt kontrolliert",
            "text": "„Leihmaterial auswählen“ beschreibt eine Auswahl. „Ausrüstung prüfen“ beschreibt eine Kontrolle. Ein Baum-Eintrag ist kein automatisch ausgeführter Arbeitsschritt. Abläufe bleiben im Prozessmodell.",
            "steps": [
              "Prüfe die Bedeutung der beiden Bausteine.",
              "Verschiebe einen Typ nur bei fachlich begründeter Änderung."
            ],
            "focus": "local.auswahl",
            "question": "Welcher Baustein beschreibt eine Auswahl?",
            "choices": [
              "Leihmaterial auswählen",
              "Ausrüstung prüfen"
            ],
            "answer": 0,
            "explanation": "Eine Entscheidung hat Alternativen. Ein Prüfschritt prüft Bedingungen oder Vollständigkeit."
          }
        ]
      },
      {
        "id": "beziehungen",
        "title": "3. Beziehungen lesen",
        "goal": "Quelle, Beziehung und Ziel als Satz lesen.",
        "slides": [
          {
            "id": "beziehungen-1",
            "title": "Eine Verbindung ist ein gerichteter Satz",
            "text": "Lies den Pfeil als Quelle, Beziehung, Ziel. Im Beispiel: „Benötigte Schutzausrüstung – belegt durch – Ausrüstungsliste“. Der Baum allein sagt diese Verbindung nicht aus.",
            "steps": [
              "Wähle die Frage als Quelle.",
              "Lies den Beziehungstyp und anschließend das Ziel."
            ],
            "focus": "local.schutz",
            "question": "Welche Richtung wird erklärt?",
            "choices": [
              "Frage wird durch Liste belegt",
              "Liste wird durch Frage belegt"
            ],
            "answer": 0,
            "explanation": "Die Pfeilrichtung gehört zur Aussage. Umkehren kann die Bedeutung verändern."
          },
          {
            "id": "beziehungen-2",
            "title": "Information und Voraussetzung sind verschiedene Aussagen",
            "text": "„Informiert“ beschreibt einen Informationsbezug. „Erfordert“ beschreibt eine benötigte Voraussetzung. „Wartet auf Prüfung“ ist eine modellierte Abhängigkeit. Der Editor führt dadurch keine Prüfung automatisch aus.",
            "steps": [
              "Wähle den Typ wegen seiner Bedeutung, nicht wegen der Pfeilfarbe.",
              "Bei mehreren möglichen Bedeutungen eine Fachfrage stellen."
            ],
            "focus": "local.auswahl",
            "question": "Was folgt aus einem Pfeil „informiert“?",
            "choices": [
              "Die Zielprüfung wurde durchgeführt",
              "Die Quelle liefert Informationen für das Ziel"
            ],
            "answer": 1,
            "explanation": "Die Beziehung beschreibt einen Zusammenhang im Modell und keinen erledigten Vorgang."
          },
          {
            "id": "beziehungen-3",
            "title": "Neue Beziehungen brauchen zwei vorhandene Bausteine",
            "text": "Im Editor öffnest du Ansicht → Verbindungen und wählst Quelle, Typ und Ziel. Prüfe den Satz vor dem Hinzufügen. Eine sachlich passende Verbindung kann Kategorien übergreifen.",
            "steps": [
              "Suche Quelle und Ziel anhand ihrer Bezeichnungen.",
              "Prüfe Richtung und Typ im gespeicherten Vergleich."
            ],
            "focus": "local.pruefung",
            "question": "Was muss vor dem Hinzufügen feststehen?",
            "choices": [
              "Nur der Name des Ziels",
              "Quelle, Beziehungstyp und Ziel"
            ],
            "answer": 1,
            "explanation": "Alle drei Teile bilden gemeinsam die fachliche Aussage."
          }
        ]
      },
      {
        "id": "pflegen",
        "title": "4. Gezielt bearbeiten",
        "goal": "Eine kleine begründete Änderung vorbereiten.",
        "slides": [
          {
            "id": "pflegen-1",
            "title": "Der erste Pflegefall präzisiert eine Bezeichnung",
            "text": "Unser künstlicher Anlass: Die Frage soll ausdrücklich Schutzausrüstung für den Workshop betreffen. Vorher: „Benötigte Schutzausrüstung“. Nachher: „Benötigte Schutzausrüstung für den Workshop“.",
            "steps": [
              "Öffne Bearbeiten und wähle den vorhandenen Baustein.",
              "Wähle Entwurf erstellen oder Bearbeiten am Baustein.",
              "Im Editor kannst du den gewünschten Baustein auch mit Rechtsklick → Bearbeiten öffnen. Ein Hinweis erklärt nicht verfügbare Befehle."
            ],
            "focus": "local.schutz",
            "question": "Brauchen wir dafür einen zweiten Baustein?",
            "choices": [
              "Ja, bei jeder Umbenennung",
              "Nein, die Bedeutung bleibt derselbe Gegenstand"
            ],
            "answer": 1,
            "explanation": "Wir präzisieren die Bezeichnung des vorhandenen Bausteins und behalten seine Kennung und Beziehungen."
          },
          {
            "id": "pflegen-2",
            "title": "Eine Erläuterung macht den Pflegegrund nachvollziehbar",
            "text": "Bezeichnung ist der kurze sichtbare Name. Fachliche Erläuterung erklärt seine Bedeutung. Offene Fachfrage hält eine ungelöste Frage fest. Der Status einer übernommenen NaC-Vorlage ist im Formular schreibgeschützt.",
            "steps": [
              "Ändere nur die begründeten Felder.",
              "Dokumentiere Unsicherheit als offene Frage statt eine Antwort zu erfinden.",
              "Beim Bearbeiten bleiben Ausschneiden, Kopieren und Einfügen in den Textfeldern verfügbar."
            ],
            "focus": "local.schutz",
            "question": "Wo gehört eine ungelöste Bedeutungsfrage hin?",
            "choices": [
              "Offene Fachfrage",
              "Als erfundene Entscheidungsoption"
            ],
            "answer": 0,
            "explanation": "Eine offene Frage bleibt sichtbar und kann fachlich geprüft werden."
          },
          {
            "id": "pflegen-3",
            "title": "Neue Bausteine und Löschungen ändern die Struktur",
            "text": "Ein neuer Baustein ist sinnvoll, wenn ein eigenständiger Gegenstand fehlt. Seine Kategorie, Bezeichnung und Beziehungen müssen erklärt werden. Beim Löschen müssen auch betroffene Beziehungen und Quellen geprüft werden.",
            "steps": [
              "Suche vor dem Anlegen nach ähnlichen Bausteinen.",
              "Prüfe nach der Änderung, ob Nachbarn oder Bezüge fehlen."
            ],
            "focus": "local.liste",
            "question": "Wann ist ein neuer Baustein begründet?",
            "choices": [
              "Ein eigenständiger benötigter Gegenstand fehlt",
              "Die alte Bezeichnung gefällt nicht"
            ],
            "answer": 0,
            "explanation": "Eine Umbenennung ist eine Feldänderung. Ein neuer Gegenstand ist eine Strukturänderung."
          }
        ]
      },
      {
        "id": "speichern",
        "title": "5. Speichern und prüfen",
        "goal": "Ungespeicherte Eingabe, gespeicherten Entwurf und fachliche Freigabe unterscheiden.",
        "slides": [
          {
            "id": "speichern-1",
            "title": "Speichern zeigt zuerst den Vergleich",
            "text": "Deine Eingaben sind zunächst ungespeichert. Datei → Speichern oder Strg+S öffnet den Vergleich. Erst Speichern bestätigen sichert die gezeigte Fassung in deinem Arbeitsentwurf. Während der Speicherung kurz warten; bei einem Fehler bleiben die Eingaben offen und können erneut gespeichert werden.",
            "steps": [
              "Vergleiche alte und neue Bezeichnung.",
              "Prüfe, ob weitere unbeabsichtigte Änderungen auftauchen."
            ],
            "focus": "local.schutz",
            "question": "Wann wird dein Arbeitsentwurf gespeichert?",
            "choices": [
              "Beim Tippen jedes Buchstabens",
              "Nach Bestätigung der Speichervorschau"
            ],
            "answer": 1,
            "explanation": "Die Vorschau zeigt die fachlichen Unterschiede. Erst deine Bestätigung sichert sie im Arbeitsentwurf."
          },
          {
            "id": "speichern-2",
            "title": "Ein gespeicherter Entwurf ist noch keine freigegebene Vorlage",
            "text": "Unter Prüfen → Meine Änderung begründest du deine Änderung und nennst die verwendete Fachquelle samt Fassung oder Datum. Zur Fachprüfung einreichen gibt den gespeicherten Entwurf an eine andere berechtigte Person zur Prüfung. Die gemeinsam verwendete Vorlage bleibt bis zur Übernahme erhalten.",
            "steps": [
              "Grund: Bezeichnung im künstlichen Workshop präzisiert.",
              "Quelle: künstliche Trainingsbeschreibung, keine Rechtsquelle."
            ],
            "focus": "local.schutz",
            "question": "Erteilt Speichern eine notarielle Freigabe?",
            "choices": [
              "Nein",
              "Ja"
            ],
            "answer": 0,
            "explanation": "Speichern, Einreichen, fachliche Freigabe und Übernahme sind getrennte Schritte."
          },
          {
            "id": "speichern-3",
            "title": "Eine neue Änderung braucht eine Prüfung des neuen Stands",
            "text": "Eine notarielle Fachfreigabe gehört zur tatsächlich geprüften Fassung einer Änderung. Weitere Änderungen müssen erneut beurteilt werden. Die verantwortliche Person für den Modellbestand übernimmt die Änderung nach der nötigen Freigabe und erfolgreichen Prüfungen.",
            "steps": [
              "Prüfe Begriffe, Quellen und Beziehungen.",
              "Prüfe vor der Übernahme, ob Freigabe und Prüfergebnisse zur aktuellen Fassung gehören."
            ],
            "focus": "local.pruefung",
            "question": "Welcher Stand ist für eine Freigabe maßgeblich?",
            "choices": [
              "Die aktuelle geprüfte Fassung",
              "Irgendeine frühere Ansicht"
            ],
            "answer": 0,
            "explanation": "Eine Freigabe ist nur aussagekräftig, wenn erkennbar ist, welcher Stand geprüft wurde."
          }
        ]
      },
      {
        "id": "routine",
        "title": "6. Pflege im Alltag",
        "goal": "Eine Änderung vollständig und wiederholbar abschließen.",
        "slides": [
          {
            "id": "routine-1",
            "title": "Ein kleiner Pflegeauftrag ist leichter zu prüfen",
            "text": "Beschreibe Anlass, betroffene Vorgangsart und erwartete Änderung vor dem Bearbeiten. Arbeite am ausgewählten Fachmodellbestand. Ein Entwurf sollte einen klaren fachlichen Zweck haben, etwa eine unklare Bezeichnung zu präzisieren.",
            "steps": [
              "Notiere die fragliche Bezeichnung oder Verbindung.",
              "Nenne den erwarteten Unterschied in einem Satz."
            ],
            "focus": "local.schutz",
            "question": "Was macht einen Pflegeauftrag nachvollziehbar?",
            "choices": [
              "Anlass und erwartete fachliche Änderung",
              "Nur ein anderer Name ohne Begründung"
            ],
            "answer": 0,
            "explanation": "Ein klarer Pflegeauftrag erklärt, was fachlich unklar ist und welchen Unterschied die Änderung bewirken soll."
          },
          {
            "id": "routine-2",
            "title": "Beispiele erklären Funktionen ohne echte Daten zu ändern",
            "text": "Die Übung verändert ausschließlich das künstliche Beispiel im Training. Deine echten Fachmodelle und Arbeitsentwürfe bleiben unberührt. Die Übung erteilt auch keine notarielle Freigabe. Neu laden setzt sie zurück.",
            "steps": [
              "Wähle unten „Bezeichnung üben“.",
              "Ändere die Beispielbezeichnung, prüfe den Vergleich und bestätige Speichern."
            ],
            "focus": "local.schutz",
            "question": "Wo wird diese Übung gespeichert?",
            "choices": [
              "Im echten Fachmodellbestand",
              "Nur im Browser bis zum Neuladen"
            ],
            "answer": 1,
            "explanation": "Der Trainingsbereich ist eine geschützte Erklärung mit künstlichen Beispielen."
          },
          {
            "id": "routine-3",
            "title": "Die Pflege endet mit einem nachgewiesenen Ergebnis",
            "text": "Eine Modelländerung ist nachvollziehbar, wenn Grund, Fachquelle, tatsächliche Änderung und geprüfte Fassung zusammengehören. Kontrolliere nach der Übernahme das Ergebnis im gemeinsamen Modellbestand. Bei einer Fehlermeldung bewahre den Entwurf und notiere Arbeitsschritt und Meldung.",
            "steps": [
              "Nutze das Handbuch für Rollen und Fehlerbehebung.",
              "Prüfe eine kleine konkrete Änderung statt mehrere Themen gleichzeitig."
            ],
            "focus": "local.vermerk",
            "question": "Was gehört zur dokumentierten Modelländerung?",
            "choices": [
              "Grund, Quelle, Änderung und geprüfter Stand",
              "Nur eine neue Überschrift"
            ],
            "answer": 0,
            "explanation": "Eine nachvollziehbare Pflege verbindet die fachliche Begründung mit der tatsächlichen Änderung und Prüfung."
          }
        ]
      }
    ]
  },
  "example": {
    "synthetic": true,
    "title": "Künstliches Beispiel: Fantasiewerkstatt",
    "nodes": [
      {
        "id": "local.schutz",
        "category": "required_information",
        "label": "Benötigte Schutzausrüstung",
        "detail": "Fragevorlage: Welche Schutzausrüstung ist für die Übung vorgesehen?"
      },
      {
        "id": "local.liste",
        "category": "documents",
        "label": "Ausrüstungsliste",
        "detail": "Dokumentart mit den vorgesehenen Ausrüstungsarten."
      },
      {
        "id": "local.auswahl",
        "category": "decisions",
        "label": "Leihmaterial auswählen",
        "detail": "Entscheidungsvorlage: eigene Ausrüstung oder Leihmaterial."
      },
      {
        "id": "local.pruefung",
        "category": "gates",
        "label": "Ausrüstung prüfen",
        "detail": "Prüfvorlage: Ausrüstungsliste und Auswahl auf Übereinstimmung prüfen."
      },
      {
        "id": "local.vermerk",
        "category": "evidence",
        "label": "Prüfvermerk",
        "detail": "Nachweisart, die eine durchgeführte Prüfung dokumentieren würde."
      }
    ],
    "edges": [
      {
        "from": "local.schutz",
        "relation": "belegtDurch",
        "to": "local.liste"
      },
      {
        "from": "local.auswahl",
        "relation": "informiert",
        "to": "local.pruefung"
      },
      {
        "from": "local.pruefung",
        "relation": "belegtDurch",
        "to": "local.vermerk"
      }
    ]
  },
  "handbook": {
    "version": 1,
    "title": "Handbuch für Ontologiepflege und notarielle Prüfung",
    "chapters": [
      {
        "id": "ueberblick",
        "title": "Produkt und Zweck",
        "paragraphs": [
          "Dieses Handbuch richtet sich an Ontologiepfleger und Notare. Mit editor8 liest und pflegst du Fachmodelle: Welche Angaben, Dokumenttypen, Entscheidungen, Prüfschritte und Nachweise gehören zu einer Vorgangsart, und wie hängen sie zusammen?",
          "Eine Ontologie beschreibt die wiederverwendbaren Begriffe und Beziehungen eines Fachgebiets. Du pflegst die Vorlage, etwa die Bedeutung einer benötigten Angabe. Die Antwort einer bestimmten Person, eine ausgefüllte Akte oder ein erledigter Prüfschritt gehören nicht in diese Vorlage.",
          "Deine Änderungen betreffen den ausgewählten Fachmodellbestand, beispielsweise „Notar-Fachmodelle“. Speichern, Einreichen und Fachprüfung beziehen sich immer auf diese Modelle. Für die Bedienung brauchst du keine Programmierkenntnisse und keinen Zugriff auf den Quellcode des Editors.",
          "Die Hilfe führt durch Verstehen, Bearbeiten und Prüfen. Training und Übungen verwenden vollständig künstliche Beispiele. Sie erläutern die Bedienung und ersetzen keine notarielle Beurteilung eines tatsächlichen Fachmodells."
        ],
        "steps": [],
        "facts": [
          [
            "Fachmodell",
            "Vorlage mit Begriffen, Eigenschaften und Beziehungen für eine Vorgangsart."
          ],
          [
            "Modellbestand",
            "Die in der Auswahl bereitgestellten Fachmodelle und gemeinsamen Begriffe, an denen du arbeitest."
          ],
          [
            "Fachliche Pflege",
            "Bezeichnungen, Erläuterungen, Bausteine und Beziehungen nachvollziehbar verbessern."
          ],
          [
            "Notarielle Fachprüfung",
            "Änderungen einer anderen Person auf Bedeutung, Quellen und Beziehungen prüfen und begründet beurteilen."
          ]
        ]
      },
      {
        "id": "einstieg",
        "title": "Einstieg und Orientierung",
        "paragraphs": [
          "Öffne https://www.ontologie8.de und melde dich mit deinem zugelassenen GitHub-Konto an. Wähle links den Fachmodellbestand, den du pflegen möchtest. Die Auswahl zeigt die für dich zugänglichen Bestände. Fehlt ein benötigter Bestand, wende dich an dessen fachlich verantwortliche Person.",
          "Links außen stehen Verstehen, Bearbeiten und Prüfen. Daneben findest du die Auswahl der Fachmodelle und den aufklappbaren Baum. In der Mitte siehst du die Zusammenhänge; rechts erscheinen Details oder Bearbeitungsfelder zum gewählten Baustein.",
          "Allgemeine Anleitungen stehen oben unter Hilfe. Das Fragezeichen am ausgewählten Baustein erläutert dessen fachlichen Kontext. Unter Informationen findest du Beschreibung, Quellen und frühere Fassungen der Vorgangsart.",
          "Mit Strg+F1 oder einem Doppelklick auf eine Registerkarte klappst du das Menüband ein oder aus. Die Menü-Schaltfläche oben links blendet den inneren Baum ein oder aus. Menüs und Auswahl bleiben erreichbar, während du innerhalb des Arbeitsbereichs blätterst oder scrollst.",
          "Halte den Mauszeiger kurz über einen Befehl, ein Feld oder einen Baustein: Ein Hinweis erklärt dessen Aufgabe. Bei Tastaturfokus erscheint der Hinweis ebenfalls. Deaktivierte Befehle erläutern, was zuerst erforderlich ist. Escape schließt den Hinweis; die ausführliche Hilfe zur Auswahl bleibt über das Fragezeichen erreichbar.",
          "Rechtsklick auf einen Baustein im Baum oder Graphen öffnet dessen Befehle: Öffnen, Bearbeiten, Verbindungen und Hilfe zur Auswahl. Das Menü gehört immer zum angeklickten Baustein. Auf einer Vorgangsart findest du Öffnen, Informationen und Drucken; auf einem gemeinsamen Begriff Öffnen, Bearbeiten und Hilfe zur Auswahl. Das Öffnen des Menüs verändert das Modell nicht."
        ],
        "steps": [
          "Den richtigen Fachmodellbestand auswählen und unter Datei → Öffnen beziehungsweise im Baum eine Vorgangsart öffnen.",
          "Unter Verstehen einen Baustein auswählen und seine Bedeutung sowie die verbundenen Bausteine lesen.",
          "Vor einer Änderung klären, was fachlich fehlt oder unklar ist; dafür unter Informationen auch die Quellen lesen.",
          "Für eine geführte Übung Hilfe → Training öffnen; für einzelne Fragen Hilfe → Handbuch oder Begriffe verwenden."
        ],
        "facts": [
          [
            "Suche oben",
            "Filtert den Baum. Eingabetaste oder Strg+K sucht Bausteine im gesamten ausgewählten Modellbestand."
          ],
          [
            "Strg+S / Datei → Speichern",
            "Öffnet den Vergleich deiner Änderungen vor dem Speichern."
          ],
          [
            "Datei → Drucken",
            "Druckt eine Lesefassung der aktuellen Auswahl."
          ],
          [
            "Umschalt+F10 / Kontextmenü-Taste",
            "Öffnet die Befehle zum fokussierten Objekt. Pfeiltasten, Pos1 und Ende wählen einen Befehl; Eingabetaste führt ihn aus. Escape schließt das Menü und kehrt zum Objekt zurück. Tab setzt die normale Tastaturbedienung fort."
          ],
          [
            "Editor-Release",
            "Versionskennung der verwendeten App in der Fußzeile; bei einer Fehlermeldung mit angeben."
          ]
        ]
      },
      {
        "id": "modell",
        "title": "Bausteine und Beziehungen",
        "paragraphs": [
          "Der Baum ordnet Bausteine nach ihrer fachlichen Art. Er zeigt keine zeitliche Reihenfolge. Der Graph zeigt, wie die Bausteine zusammenhängen; eine Beziehung kann unterschiedliche Kategorien verbinden.",
          "Fragen beschreiben, welche Angabe benötigt wird. Dokumenttypen beschreiben Arten von Dokumenten. Entscheidungen benennen Auswahlpunkte. Prüfschritte beschreiben zu prüfende Bedingungen. Nachweistypen beschreiben Arten von Belegen. Die tatsächliche Antwort oder das ausgefüllte Dokument gehört nicht in die Vorlage.",
          "Ein Dokument kann zugleich als Beleg dienen. Entscheidend ist sein fachlicher Zweck im jeweiligen Modell. Wenn die Zuordnung unklar ist, lies die Erläuterung und halte die ungeklärte Bedeutung als Offene Fachfrage fest.",
          "Lies jede Verbindung als Satz: Ausgangspunkt – Beziehung – Ziel. Im künstlichen Beispiel wird „Benötigte Schutzausrüstung“ durch „Ausrüstungsliste“ belegt. Die Verbindung beschreibt die Vorlage; sie bestätigt keine tatsächlich durchgeführte Prüfung."
        ],
        "steps": [],
        "facts": [
          [
            "Fragen",
            "Welche Information wird benötigt? Beispiel: benötigte Schutzausrüstung."
          ],
          [
            "Dokumenttypen",
            "Welche Dokumentart ist vorgesehen? Beispiel: Ausrüstungsliste."
          ],
          [
            "Entscheidungen",
            "Welche Auswahl soll getroffen werden? Beispiel: Leihmaterial auswählen."
          ],
          [
            "Prüfschritte",
            "Welche Bedingung soll geprüft werden? Beispiel: Ausrüstung prüfen."
          ],
          [
            "Nachweistypen",
            "Welche Art von Beleg ist vorgesehen? Beispiel: Prüfvermerk."
          ],
          [
            "erfordert",
            "Der Ausgangspunkt benötigt das Ziel als Voraussetzung."
          ],
          [
            "informiert",
            "Der Ausgangspunkt liefert Informationen für das Ziel."
          ],
          [
            "belegt durch",
            "Der Ausgangspunkt wird durch das Ziel belegt."
          ],
          [
            "wartet auf vollständige Angaben / wartet auf Prüfung",
            "Beschreibt eine Abhängigkeit in der Vorlage; führt die Prüfung nicht selbst durch."
          ],
          [
            "erfordert Entscheidung / füllt / bestimmt",
            "Beschreibt eine weitere fachliche Verbindung. Prüfe die Bedeutung und Pfeilrichtung vor einer Änderung."
          ]
        ]
      },
      {
        "id": "pflege",
        "title": "Modellpflege Schritt für Schritt",
        "paragraphs": [
          "Beginne mit einem kleinen fachlichen Auftrag: Welche Bezeichnung, Erläuterung oder Beziehung ist unklar? Was soll sich ändern, und welche Quelle begründet die Änderung? Suche zuerst nach vorhandenen Bausteinen, damit kein doppelter Begriff entsteht.",
          "Eine Umbenennung präzisiert einen vorhandenen Gegenstand. Ein neuer Baustein ist sinnvoll, wenn ein eigenständiger Gegenstand fehlt. Er braucht eine passende Art, eine verständliche Bezeichnung, eine Erläuterung und die nötigen Beziehungen. Vor dem Löschen prüfst du die verbundenen Bausteine und Quellen.",
          "Die künstliche Übung „Fantasiewerkstatt“ präzisiert „Benötigte Schutzausrüstung“ zu „Benötigte Schutzausrüstung für den Workshop“. Der Gegenstand, seine Kennung und seine Beziehungen bleiben erhalten. In der Übung änderst du ausschließlich das Beispiel; echte Fachmodelle bleiben unberührt.",
          "Du kannst Bearbeiten auch per Rechtsklick auf den gewünschten Baustein wählen. Der Editor beginnt bei Bedarf einen Arbeitsentwurf und öffnet genau diesen Baustein. Speichern zeigt weiterhin zuerst den Vergleich; erst deine Bestätigung sichert die Änderung. Entfernen ist nur für zusätzlich angelegte Bausteine verfügbar und fragt vorher nach. Ein Baustein aus der Vorlage wird dadurch nicht gelöscht.",
          "Beim Bearbeiten von Text bleiben Ausschneiden, Kopieren und Einfügen über die rechte Maustaste verfügbar. Ungespeicherte Eingaben bleiben beim Wechsel der Bausteinauswahl im Entwurf erhalten. Für den Wechsel zu einer anderen Vorgangsart prüfe zuerst den Speicherstatus."
        ],
        "steps": [
          "Unter Verstehen die Vorgangsart, den betroffenen Baustein, seine Beziehungen und Quellen prüfen.",
          "Links Bearbeiten wählen und Entwurf erstellen oder Bearbeiten am Baustein öffnen.",
          "Bezeichnung und Fachliche Erläuterung gezielt ändern; ungelöste Bedeutung als Offene Fachfrage festhalten.",
          "Für eine Verbindung Ansicht → Verbindungen öffnen, Quelle, Beziehungstyp und Ziel wählen und den entstehenden Satz lesen.",
          "Datei → Speichern wählen, alle angezeigten Unterschiede prüfen und Speichern bestätigen.",
          "Unter Prüfen → Meine Änderung Grund und Quellenstand angeben und Zur Fachprüfung einreichen wählen."
        ],
        "facts": [
          [
            "Neue Vorgangsart benötigt",
            "Im Editor kannst du bestehende Vorgangsarten pflegen. Für die Aufnahme einer weiteren Vorgangsart wende dich an die verantwortliche Person für den Modellbestand."
          ],
          [
            "Gemeinsame Begriffe",
            "Gelten für mehrere Vorgangsarten. Ihre Pflege benötigt einen eigenen Entwurf und eine zusätzliche fachliche Berechtigung."
          ],
          [
            "Kennung",
            "Bleibende Identität eines Gegenstands. Eine präzisere Bezeichnung erzeugt keinen neuen Gegenstand."
          ]
        ]
      },
      {
        "id": "felder",
        "title": "Feldreferenz",
        "paragraphs": [
          "Die Bearbeitungsfelder beschreiben den ausgewählten fachlichen Baustein. Nicht jedes Feld ist für jede Bausteinart erforderlich. Ändere nur die Angaben, die dein Pflegeauftrag begründet.",
          "Kennungen und der Status einer übernommenen NaC-Vorlage sind geschützt. Bestehende Entscheidungswerte bleiben erhalten, bis eine fachlich abgestimmte Änderung vorliegt. Die angezeigte Verwendung eines Begriffs beschreibt Bezüge zwischen Vorlagen, keine tatsächlichen Zugriffe auf Akten."
        ],
        "steps": [],
        "facts": [
          [
            "Bezeichnung",
            "Kurzer verständlicher Name. Beispiel: Benötigte Schutzausrüstung für den Workshop."
          ],
          [
            "Bausteintyp",
            "Fachliche Art des Gegenstands, etwa Frage oder Dokumenttyp. Eine Änderung braucht eine fachliche Begründung."
          ],
          [
            "Fachliche Erläuterung",
            "Bedeutung und Abgrenzung des Bausteins. Was ist gemeint, und wofür wird er benötigt?"
          ],
          [
            "Offene Fachfrage",
            "Ungelöste Frage zur Bedeutung oder Modellierung, die fachlich geklärt werden muss."
          ],
          [
            "Abschnitt der Vorlage",
            "Bezug zum passenden Abschnitt der fachlichen Vorlage."
          ],
          [
            "Status der NaC-Vorlage",
            "Status der übernommenen Quelle; bei übernommenen Bausteinen schreibgeschützt."
          ],
          [
            "Pflegestatus des lokalen Entwurfs",
            "Status eines im Modellbestand ergänzten Bausteins; keine notarielle Freigabe."
          ],
          [
            "Verantwortliche Rolle",
            "Fachliche Zuständigkeit für die betreffende Angabe oder Prüfung."
          ],
          [
            "Datenschutzklasse / Kann Personendaten enthalten?",
            "Einordnung der vorgesehenen Angabe; hier keine tatsächlichen Personendaten eintragen."
          ],
          [
            "Benötigt für / Entscheidungsoptionen",
            "Eine Angabe pro Zeile. Bestehende Auswahlwerte nur nach fachlicher Abstimmung ändern."
          ],
          [
            "Dokumentquelle",
            "Quellenbezug des Dokumenttyps, etwa das maßgebliche Dokument und dessen Fassung."
          ],
          [
            "Grund und Quellenstand beim Einreichen",
            "Warum sich das Fachmodell ändert und auf welche Quelle samt Fassung oder Datum du dich stützt."
          ]
        ]
      },
      {
        "id": "pruefen",
        "title": "Entwurf, Prüfung und Übernahme",
        "paragraphs": [
          "Beim Bearbeiten sind deine Eingaben zunächst ungespeichert. Speichern öffnet den Vergleich; Speichern bestätigen sichert die gezeigten Änderungen in deinem Arbeitsentwurf. Einreichen gibt den gespeicherten Entwurf zur Fachprüfung. Die gemeinsam verwendete Vorlage wird dadurch noch nicht ersetzt.",
          "Unter Fachprüfung prüft eine andere berechtigte Person den Änderungsgrund, die Quellen und die Auswirkungen auf Begriffe und Beziehungen. Eine notarielle Freigabe benötigt die entsprechende fachliche Berechtigung. Du kannst deine eigene Änderung nicht selbst freigeben.",
          "Eine Freigabe gehört zur tatsächlich geprüften Fassung. Wird die Änderung danach weiter bearbeitet, muss die neue Fassung erneut beurteilt werden. Die verantwortliche Person für den Modellbestand übernimmt die Änderung erst nach der nötigen Fachfreigabe und erfolgreichen Prüfungen. Falls nötig, öffnet sie dafür den Änderungsvorschlag über In GitHub öffnen.",
          "Gespeicherte Arbeitsentwürfe kannst du später wieder öffnen. Entwurf ablegen beendet die aktuelle Bearbeitung, ohne bereits gespeicherte Änderungen zu löschen. Beim Abmelden fragt der Editor vor dem Verwerfen offener Eingaben. Ungespeicherte Eingaben sind beim Schließen des Browsers nicht dauerhaft gesichert.",
          "Gespeichert wird genau die bestätigte Vorschau. Änderst du die Eingaben während ihrer Vorbereitung, wähle Speichern erneut. Während des Schreibens wartest du auf die Bestätigung. Bei einem Fehler bleiben die Eingaben erhalten und die Vorschau erlaubt einen erneuten Versuch.",
          "Unter Informationen kannst du frühere Fassungen ansehen. Die Wiederaufnahme einer früheren Fassung erzeugt nach Vergleich einen neuen Arbeitsentwurf. Auch dieser braucht Begründung und Fachprüfung."
        ],
        "steps": [
          "Unter Prüfen → Fachprüfung eine eingereichte Änderung öffnen und ihren Anlass sowie Quellenstand lesen.",
          "Begriffe und Fachfragen, Rechtsquellen und Quellenstand sowie Beziehungen und fachliche Wirkung erst nach der jeweiligen inhaltlichen Prüfung markieren.",
          "Eine nachvollziehbare Begründung schreiben und Änderung anfordern oder mit entsprechender Berechtigung Fachlich freigeben wählen.",
          "Bei weiteren Änderungen die neue Fassung erneut prüfen.",
          "Nach der Übernahme im gemeinsamen Modellbestand kontrollieren, ob die beabsichtigte fachliche Änderung sichtbar ist."
        ],
        "facts": [
          [
            "Ungespeicherte Eingaben",
            "Noch nicht im Arbeitsentwurf gesichert."
          ],
          [
            "Gespeicherter Arbeitsentwurf",
            "Deine gesicherte Änderung; weiterhin getrennt von der gemeinsam verwendeten Vorlage."
          ],
          [
            "Eingereichte Änderung",
            "Zur Fachprüfung bereitgestellt; noch keine Freigabe."
          ],
          [
            "Fachlich freigegeben",
            "Eine dazu berechtigte andere Person hat die bezeichnete Fassung geprüft und freigegeben."
          ],
          [
            "Übernommen",
            "Die Änderung ist im gemeinsam verwendeten Modellbestand enthalten."
          ]
        ]
      },
      {
        "id": "rollen",
        "title": "Fachliche Rollen und Zugang",
        "paragraphs": [
          "Dein GitHub-Konto dient der Anmeldung und ordnet Änderungen sowie Prüfentscheidungen deiner Person zu. Welche Fachmodelle du lesen oder bearbeiten darfst, wird für den jeweiligen Modellbestand festgelegt. Die Auswahl eines Bestands erteilt keine zusätzlichen Rechte.",
          "Leseberechtigte verstehen und vergleichen die Vorlagen. Ontologiepfleger bearbeiten sie in Arbeitsentwürfen und reichen begründete Änderungen ein. Zur notariellen Fachprüfung berechtigte Notare können die Änderung einer anderen Person fachlich freigeben. Die Pflege gemeinsamer Begriffe ist eine zusätzliche fachliche Aufgabe.",
          "Fehlt dir ein Modellbestand oder eine nötige Funktion, wende dich an die dafür verantwortliche Person und nenne den Bestand sowie die gewünschte Tätigkeit. Diese Hilfe erklärt deine fachliche Arbeit im Editor. Zugang und fachliche Berechtigungen werden außerhalb deiner Modelländerung verwaltet."
        ],
        "steps": [],
        "facts": [
          [
            "Leseberechtigte",
            "Fachmodelle ansehen, Zusammenhänge verstehen und Quellen lesen."
          ],
          [
            "Ontologiepfleger",
            "Bausteine und Beziehungen bearbeiten, Entwürfe speichern und zur Fachprüfung einreichen."
          ],
          [
            "Notarielle Fachprüfer",
            "Änderungen anderer Personen prüfen, Rückfragen dokumentieren und mit der nötigen Berechtigung fachlich freigeben."
          ],
          [
            "Pflege gemeinsamer Begriffe",
            "Gemeinsam verwendete Begriffe und Beziehungstypen innerhalb des ausgewählten Modellbestands pflegen; zusätzliche Berechtigung erforderlich."
          ],
          [
            "Verantwortliche Person für den Modellbestand",
            "Ansprechpartner für fachlichen Umfang, Zugang, Pflegezuständigkeiten und Übernahme geprüfter Änderungen."
          ]
        ]
      },
      {
        "id": "fehler",
        "title": "Wenn etwas nicht funktioniert",
        "paragraphs": [
          "Notiere bei einem Fehler den ausgewählten Fachmodellbestand, die Vorgangsart, deinen Arbeitsschritt und die angezeigte Fehlermeldung. Gib bei einer technischen Störung auch den Editor-Release aus der Fußzeile an. Melde die Störung dem Betreiber; fachliche Unklarheiten gehen an die verantwortliche Person für den Modellbestand.",
          "Gib keine Anmeldedaten oder vollständigen Rückkehradressen der Anmeldung weiter. Bewahre gespeicherte Entwürfe, solange ein Fehler ungeklärt ist. Nach einem Speicherfehler bleiben Eingaben offen: Warte auf die Meldung, prüfe die Vorschau und versuche die Speicherung erneut.",
          "Im Training übst du an einem künstlichen Modell. Die Übung verändert keine echten Fachmodelle und erteilt keine notarielle Freigabe. Neu laden setzt die Übung zurück."
        ],
        "steps": [],
        "facts": [
          [
            "Anmeldung nicht abgeschlossen",
            "Auf der Fehlerseite Erneut anmelden wählen. Bei erneutem Fehler nur Meldung und Diagnose-Kennung an den Betreiber geben; keine vollständige Anmeldeadresse weitergeben."
          ],
          [
            "Fachmodellbestand fehlt",
            "Zugang bei der verantwortlichen Person für diesen Bestand klären lassen."
          ],
          [
            "Speichern deaktiviert",
            "Prüfen, ob du eine Änderung eingegeben hast und ein passender Arbeitsentwurf geöffnet ist. Eine laufende Speicherung zunächst abwarten."
          ],
          [
            "Stand hat sich inzwischen geändert",
            "Den aktuellen Modellstand neu lesen und mit deinem Entwurf vergleichen, bevor du weitere Änderungen bestätigst."
          ],
          [
            "Freigabe deaktiviert",
            "Prüfen, ob es deine eigene Änderung ist, eine Fachprüfberechtigung fehlt oder eine angezeigte Abweichung noch geklärt werden muss."
          ],
          [
            "Wechsel des Modellbestands blockiert",
            "Zuerst offene Eingaben speichern oder bewusst verwerfen und den geöffneten Entwurf ablegen."
          ],
          [
            "Oberfläche wirkt veraltet",
            "Offene Eingaben zuerst sichern, dann die App neu laden. Bei weiterhin abweichender Anzeige den Betreiber mit Editor-Release und Fehlermeldung informieren."
          ],
          [
            "Training zurückgesetzt",
            "Übungen werden nur bis zum Neuladen gehalten. Das künstliche Beispiel erneut öffnen."
          ]
        ]
      }
    ]
  },
  "categories": {
    "required_information": "Fragen",
    "documents": "Dokumenttypen",
    "decisions": "Entscheidungen",
    "gates": "Prüfschritte",
    "evidence": "Nachweistypen"
  }
};
