# SPDX-License-Identifier: AGPL-3.0-or-later
"""Validate artificial learning examples and build the shared course/handbook."""
import argparse
import json
from pathlib import Path
from data_contract import CATEGORIES, EDGES

ROOT = Path(__file__).resolve().parents[1]

def outputs():
    def read(path):
        return json.loads((ROOT / path).read_text(encoding="utf-8"))
    course = read("training/course.json")
    example = read("training/examples/workshop.json")
    handbook = read("docs/product/handbook.json")
    if course.get("synthetic") is not True or example.get("synthetic") is not True:
        raise ValueError("Training must explicitly use artificial examples")
    ids = [node["id"] for node in example["nodes"]]
    if len(set(ids)) != len(ids) or any(n["category"] not in CATEGORIES for n in example["nodes"]):
        raise ValueError("Invalid example nodes")
    for edge in example["edges"]:
        if edge["from"] not in ids or edge["to"] not in ids or edge["relation"] not in EDGES.values():
            raise ValueError("Invalid example relationship")
    lesson_ids = [item["id"] for item in course["lessons"]]
    chapter_ids = [item["id"] for item in handbook["chapters"]]
    if len(set(lesson_ids)) != len(lesson_ids) or len(set(chapter_ids)) != len(chapter_ids):
        raise ValueError("Duplicate learning section")
    slides = [slide for lesson in course["lessons"] for slide in lesson["slides"]]
    if len({s["id"] for s in slides}) != len(slides):
        raise ValueError("Duplicate slide")
    for slide in slides:
        if slide["focus"] not in ids or type(slide["answer"]) is not int or not 0 <= slide["answer"] < len(slide["choices"]):
            raise ValueError("Invalid exercise or focus")
    result = {}
    category_labels = {key: label for key, (_, label) in CATEGORIES.items()}
    category_labels.update(required_information="Fragen", gates="Prüfschritte")
    data = dict(course=course, example=example, handbook=handbook,
                categories=category_labels)
    result["editor/learning/content.js"] = "// Generated by scripts/build_learning.py; content: CC-BY-4.0\nwindow.EDITOR8_LEARNING = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"
    links = []
    for chapter in handbook["chapters"]:
        name = chapter["id"] + ".md"
        links.append(f'- [{chapter["title"]}]({name})')
        lines = [f'# {chapter["title"]}', '', *sum(([p, ''] for p in chapter["paragraphs"]), [])]
        if chapter["steps"]:
            lines += ["## Vorgehen", ""] + [f'{i+1}. {step}' for i, step in enumerate(chapter["steps"])] + [""]
        if chapter["facts"]:
            lines += ["## Referenz", "", "| Begriff oder Meldung | Erläuterung |", "| --- | --- |"]
            lines += [f'| {a.replace("|", "/")} | {b.replace("|", "/")} |' for a, b in chapter["facts"]]
            lines += [""]
        lines += ["[Zur Übersicht](README.md) · [Training](../../training/README.md)", ""]
        result["docs/product/" + name] = "\n".join(lines)
    result["docs/product/README.md"] = "# " + handbook["title"] + "\n\nDieses Handbuch richtet sich an Ontologiepfleger und Notare. Es erklärt die fachliche Arbeit mit den ausgewählten Modellen: Verstehen, Bearbeiten und Prüfen.\n\n" + "\n".join(links) + "\n\nIm Editor unter **Hilfe → Handbuch** öffnen. Der [Grundkurs](../../training/README.md) erklärt dieselben Aufgaben mit künstlichen Beispielen. Inhalt: CC-BY-4.0.\n"
    lines = ["# Ontologien verstehen und pflegen", "", "Grundkurs für Ontologiepfleger und Notare. Künstliches Beispiel: Fantasiewerkstatt. Die Übungen verändern keine echten Fachmodelle und erteilen keine notarielle Freigabe.", ""]
    for lesson in course["lessons"]:
        lines += [f'## {lesson["title"]}', "", lesson["goal"], ""]
        for slide in lesson["slides"]:
            lines += [f'### {slide["title"]}', "", slide["text"], ""]
            lines += [f'- {step}' for step in slide["steps"]]
            lines += ["", f'**Lernfrage:** {slide["question"]}', "", f'**Erklärung:** {slide["explanation"]}', ""]
    result["training/course.md"] = "\n".join(lines)
    return result

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, text in outputs().items():
        target = ROOT / path
        if args.check:
            if not target.exists() or target.read_text(encoding="utf-8") != text:
                stale.append(path)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Stale learning material: " + ", ".join(stale))
    print("Learning examples, handbook and slide sources verified" if args.check else "Learning material generated")

if __name__ == "__main__":
    main()
